### ISSUE TITLE
missing all.json and   meta data for each version

### ISSUE THREAD

**Issue by dingdaoyi** [artipie/npm-adapter#10]
eg:  Jfrog Artifactory structure
.npm/
-@avenueui/
--flint/
---@avenueui/
       **--- flint-0.0.1-snapshot1.0.json**
       --- flint-0.0.2-snapshot1.0.json
      --package.json
 **- all.josn**

**Comment by Sammers21** [comment]
@dingdaoyi, do you think we should follow Jfrog Artifactory file structure?

**Comment by dingdaoyi** [comment]
Does not affect business can be generated without，if there is a need, I will do it myself

**Comment by Sammers21** [comment]
@dingdaoyi, following Jfrog file structure, is not required to implement npm registry.
