### ISSUE TITLE
The ‘time’ field is lost during meta.json update. Only the ‘created ’field is displayed.

### ISSUE THREAD

**Issue by dingdaoyi** [artipie/npm-adapter#119]
"time": {
        "1.0.4": "2018-07-25T03:23:08.183Z",
        "1.0.5": "2018-07-25T03:48:17.879Z",
        "1.0.6": "2018-07-25T06:32:03.849Z",
        "1.0.7": "2018-07-25T07:00:53.925Z",
        "1.0.0": "2018-07-24T03:36:13.102Z",
        "1.1.4": "2018-08-22T04:03:22.977Z",
        "1.0.2": "2018-07-24T05:43:35.163Z",
        "1.0.3": "2018-07-25T03:13:39.348Z",
        "1.0.8": "2018-07-25T07:06:46.138Z",
        "1.0.9": "2018-07-25T07:11:44.865Z",
        "1.1.2": "2018-08-15T09:50:45.190Z",
        "1.1.5": "2018-08-22T04:08:19.853Z",
        "1.1.6": "2018-08-22T05:50:17.928Z",
        "1.1.1": "2018-07-25T08:29:09.395Z",
        "1.2.6": "2018-08-24T09:42:13.288Z",
        "1.3.7": "2018-09-10T03:28:14.031Z",
        "1.3.6": "2018-08-29T04:00:08.109Z",
        "1.3.9": "2019-01-22T06:37:50.307Z",
        "1.3.8": "2018-10-27T03:31:00.920Z",
        "1.1.0": "2018-07-25T08:19:19.249Z",
        "created": "2018-07-24T03:36:13.042Z",
        "modified": "2019-03-16T06:25:04.545Z",
        "1.3.13": "2019-03-15T10:22:00.052Z",
        "1.3.12": "2019-03-15T10:15:09.479Z",
        "1.3.11": "2019-01-28T08:30:23.246Z",
        "1.3.10": "2019-01-28T08:26:51.759Z",
        "1.3.14": "2019-03-16T06:25:01.896Z",
        "1.1.3": "2018-08-16T02:32:50.644Z"
    },

**Comment by olegmoz** [comment]
@dingdaoyi thanks for the report. Could you please provide example of `meta.json` file you expect and one you actually receive?

**Comment by dingdaoyi** [comment]
@olegmoz 
{
    "name": "test-test-test-test",
    "license": "ISC",
    "versions": {
        "2.2.1": {
            "gitHead": "f02c87f395dde996644b930c984feeef8fbe5f78",
            "_id": "test-test-test-test@2.2.1",
            "dist": {
                "tarball": "http://mirrors.tools.huawei.com/npm/test-test-test-test/-/test-test-test-test-2.2.1.tgz",
                "shasum": "0a28faf7911b579dce4293757c0c259a92dc4a4d"
            },
            "name": "test-test-test-test",
            "license": "ISC",
            "author": "",
            "_shasum": "0a28faf7911b579dce4293757c0c259a92dc4a4d",
            "_npmOperationalInternal": {
                "tmp": "tmp/test-test-test-test-2.2.1.tgz_1454884953778_0.12809185381047428",
                "host": "packages-6-west.internal.npmjs.com"
            },
            "maintainers": [
                {
                    "name": "ag_dubs",
                    "email": "ashley666ashley@gmail.com"
                }
            ],
            "_npmUser": {
                "name": "ag_dubs",
                "email": "ashley666ashley@gmail.com"
            },
            "_nodeVersion": "5.4.1",
            "_npmVersion": "3.5.3",
            "version": "2.2.1",
            "scripts": {
                "test": "echo \"Error: no test specified\" && exit 1"
            },
            "keywords": [],
            "_from": ".",
            "main": "index.js",
            "description": ""
        },
        "2.2.0": {
            "gitHead": "7a3dd53015fdc2d7afb1ac7a010ed8f6442ae033",
            "_id": "test-test-test-test@2.2.0",
            "dist": {
                "tarball": "http://mirrors.tools.huawei.com/npm/test-test-test-test/-/test-test-test-test-2.2.0.tgz",
                "shasum": "8ecdb7163f5b7f7b6fcdf52cbdc64652d9c73621"
            },
            "name": "test-test-test-test",
            "license": "ISC",
            "author": "",
            "_shasum": "8ecdb7163f5b7f7b6fcdf52cbdc64652d9c73621",
            "_npmOperationalInternal": {
                "tmp": "tmp/test-test-test-test-2.2.0.tgz_1454884851789_0.07357129151932895",
                "host": "packages-9-west.internal.npmjs.com"
            },
            "maintainers": [
                {
                    "name": "ag_dubs",
                    "email": "ashley666ashley@gmail.com"
                }
            ],
            "_npmUser": {
                "name": "ag_dubs",
                "email": "ashley666ashley@gmail.com"
            },
            "_nodeVersion": "4.2.6",
            "_npmVersion": "2.14.18",
            "version": "2.2.0",
            "scripts": {
                "test": "echo \"Error: no test specified\" && exit 1"
            },
            "keywords": [],
            "_from": ".",
            "main": "index.js",
            "description": ""
        },
        "2.2.3": {
            "gitHead": "46ef08101ae248ffe446ec09e4145652037b34d8",
            "_id": "test-test-test-test@2.2.3",
            "dist": {
                "tarball": "http://mirrors.tools.huawei.com/npm/test-test-test-test/-/test-test-test-test-2.2.3.tgz",
                "shasum": "7d08f5e0f74aa9f04904726c9f787f1bb3c50027"
            },
            "name": "test-test-test-test",
            "license": "ISC",
            "author": "",
            "_shasum": "7d08f5e0f74aa9f04904726c9f787f1bb3c50027",
            "_npmOperationalInternal": {
                "tmp": "tmp/test-test-test-test-2.2.3.tgz_1454962284207_0.866266553523019",
                "host": "packages-5-east.internal.npmjs.com"
            },
            "maintainers": [
                {
                    "name": "ag_dubs",
                    "email": "ashley666ashley@gmail.com"
                }
            ],
            "_npmUser": {
                "name": "ag_dubs",
                "email": "ashley666ashley@gmail.com"
            },
            "_nodeVersion": "5.4.1",
            "_npmVersion": "3.5.3",
            "version": "2.2.3",
            "scripts": {
                "test": "echo \"Error: no test specified\" && exit 1"
            },
            "keywords": [],
            "_from": ".",
            "main": "index.js",
            "description": "*wow we need to fix this*"
        },
        "2.2.2": {
            "gitHead": "a17842da0cbf6554cd836534c317e789a2b1bb03",
            "_id": "test-test-test-test@2.2.2",
            "dist": {
                "tarball": "http://mirrors.tools.huawei.com/npm/test-test-test-test/-/test-test-test-test-2.2.2.tgz",
                "shasum": "bf13923dbad5838eefb0b1790c68d424a1bbe273"
            },
            "name": "test-test-test-test",
            "license": "ISC",
            "author": "",
            "_shasum": "bf13923dbad5838eefb0b1790c68d424a1bbe273",
            "_npmOperationalInternal": {
                "tmp": "tmp/test-test-test-test-2.2.2.tgz_1454962195750_0.7703372582327574",
                "host": "packages-5-east.internal.npmjs.com"
            },
            "maintainers": [
                {
                    "name": "ag_dubs",
                    "email": "ashley666ashley@gmail.com"
                }
            ],
            "_npmUser": {
                "name": "ag_dubs",
                "email": "ashley666ashley@gmail.com"
            },
            "_nodeVersion": "5.4.1",
            "_npmVersion": "3.5.3",
            "version": "2.2.2",
            "scripts": {
                "test": "echo \"Error: no test specified\" && exit 1"
            },
            "keywords": [],
            "_from": ".",
            "main": "index.js",
            "description": "*README.md* *FOO.md* *CONTRIBUTING.md* *package.json* *index.html*"
        }
    },
    "_rev": "1-bcad8597ec85d7fe5463bc0b68eedebb",
    "time": {
        "created": "2016-02-07T22:40:56.051Z",
        "modified": "2016-02-08T20:11:25.869Z",
        "2.2.1": "2016-02-07T22:42:36.378Z",
        "2.2.0": "2016-02-07T22:40:56.051Z",
        "2.2.3": "2016-02-08T20:11:25.869Z",
        "2.2.2": "2016-02-08T20:09:57.171Z"
    },
    "keywords": [],
    "maintainers": [
        {
            "name": "ag_dubs",
            "email": "ashley666ashley@gmail.com"
        }
    ],
    "readmeFilename": "README.md",
    "dist-tags": {
        "latest": "2.2.3"
    },
    "readme": "# test all the things\n*wow we need to fix this*\n\n\n*README.md*\n*FOO.md*\n*CONTRIBUTING.md*\n*package.json*\n*index.html*\n",
    "_id": "test-test-test-test",
    "description": "*wow we need to fix this*"
}

**Comment by olegmoz** [comment]
@genryxy could you please try to reproduce this issue with example JSON?

**Comment by genryxy** [comment]
@olegmoz yeah, I'll try

**Comment by genryxy** [comment]
@olegmoz I've investigated this problem
In class `UploadSliceTest` in method `uploadsFilesToRemote` create json file like that (currently json is being created without a version)
```
final String json = Json.createObjectBuilder()
            .add("name", "@hello/simple-npm-project")
            .add("_id", "1.0.1")
            .add("readme", "Some text")
            .add(
                "time",
                Json.createObjectBuilder()
                    .add("created", OffsetDateTime.now().minusDays(100).toString())
                    .add("modified", OffsetDateTime.now().minusDays(10).toString())
                    .add("1.0.0", OffsetDateTime.now().minusDays(50).toString())
                    .add("1.0.1", OffsetDateTime.now().minusDays(30).toString())
            )
            .add("versions", Json.createObjectBuilder())
            .add("dist-tags", Json.createObjectBuilder())
            .add("_attachments", Json.createObjectBuilder())
            .build().toString();
```
`meta.json` that was saved in storage. Even `created` tag is wrong
```
{
    "name":"@hello/simple-npm-project",
    "_id":"1.0.1",
    "readme":"Some text",
    "time":{
        "created":"2020-10-13T16:21:11.7403732"
    },
    "users":{},
    "versions":{},
    "dist-tags":{}
}
```
This problem occurs because `NpmPublishJsonToMetaSkelethon#skeleton` doesn't work properly. This class is used in `Npm#updateMetaFile`. And `Npm` is used in `UploadSlice` and other slices.

**Comment by olegmoz** [comment]
@genryxy thanks for figuring it out, could you please add a disabled test for reproducing this issue?

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#119` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.6`

**Comment by olegmoz** [comment]
@yegor256 please touch `.rultor.yml` to allow creating new NPM release

**Comment by olegmoz** [comment]
@yegor256 please touch `.rultor.yml` to allow creating new NPM release

**Comment by yegor256** [comment]
@olegmoz done in 322b23b

**Comment by olegmoz** [comment]
@yegor256 thanks!

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.6`

**Comment by olegmoz** [comment]
@dingdaoyi release `0.7.6` is ready with fix for problem you reported
