### ISSUE TITLE
Remove base path support feature

### ISSUE THREAD

**Issue by olegmoz** [artipie/npm-adapter#120]
Base path support is not required in NPM. In Artipie it should be established on upper level.
Base path is used in NPM to build absolute URLs to stored artifacts, base URL should be used instead to allow NPM be hosted on any port and protected by a reverse proxy.

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7`

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#120` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.1`

**Comment by olegmoz** [comment]
@olenagerasimova new release is ready, please try it

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.2`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.3`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.4`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.5`

**Comment by olegmoz** [comment]
@yegor256 please touch `.rultor.yaml` once again, there were changes to project structure

**Comment by yegor256** [comment]
@olegmoz done

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.5`

**Comment by olegmoz** [comment]
@yegor256 thanks!

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.5`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.5`
