### ISSUE TITLE
Fix and enable integration test NpmCommandsTest

### ISSUE THREAD

**Issue by olegmoz** [artipie/npm-adapter#122]
`NpmCommandsTest` is currently disabled. It seems that the problem with the test is rather minor and caused by change of paths in the repository. The test should be fixed and enabled at least for Unix OS

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#122` is not assigned, can't get performer
