### ISSUE TITLE
NPM proxy should be added to project

### ISSUE THREAD

**Issue by olegmoz** [artipie/npm-adapter#123]
NPM proxy is currently located in project `npm-proxy-adapter`, but there is no point in keeping it in separate project. Entry point class `NpmProxySlice` should be moved to root project with all it's dependencies

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#129](https://github.com/artipie/npm-adapter/issues/129) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#123` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#129](https://github.com/artipie/npm-adapter/issues/129) is solved here.
