### ISSUE TITLE
Remove Codecov from CI checks

### ISSUE THREAD

**Issue by olegmoz** [artipie/npm-adapter#124]
Now uploading to Codecov is done inside build pipeline which makes it fail when the service is unavailable. This should be resolved by removing Codecov from  CI checks and enabling it as optional process using GitHub integration

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#124` is not assigned, can't get performer
