### ISSUE TITLE
Run NPM command in integration tests using Docker

### ISSUE THREAD

**Issue by olegmoz** [artipie/npm-adapter#127]
Now integration tests in the project are running NPM command on local machine and so require NPM utility to be installed. To make it easier to run the tests NPM command should not be required. This can be archived by running it inside Docker container as it is done in Artipie integration tests and other adapters.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#127` is not assigned, can't get performer
