### ISSUE TITLE
NpmCommandsTest.java:114-118: Fix and enable...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-adapter#129]
The puzzle `123-9c583b0d` from #123 has to be resolved: 

https://github.com/artipie/npm-adapter/blob/a441bfd44b8d695a9040748c30fce007aabe530a/src/test/java/com/artipie/npm/NpmCommandsTest.java#L114-L118

The puzzle was created by @olegmoz on 28-Sep-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
You @genryxy[/z](https://www.0crat.com/u/genryxy) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#129` is not assigned, can't get performer
