### ISSUE TITLE
npm ERR! notarget No matching version found for *@latest.

### ISSUE THREAD

**Issue by dingdaoyi** [artipie/npm-adapter#13]
The meta.json generated by the artipie / npm-adapter code is missing some necessary fields, 
 use npm client exec the command “npm install @ avnewu / emo ”.
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ avnewu / emo @ latest.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
I tink that we can add useful fields that can be obtained at com.artipie.npm.NpmPublishJsonToMetaBind # bind, including dist-tag, repository, lincense, author

**Comment by Sammers21** [comment]
@dingdaoyi , please provide more details. what is `@avnewu / em`?

**Comment by dingdaoyi** [comment]
@Sammers21 Dear, npm install does not specify the version, it will download the best version saved in dist-tag in package.json, @avnewu / em is just a project

**Comment by Sammers21** [comment]
i guess this issue were closed int #19

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#13` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
