### ISSUE TITLE
Integration tests are not performed

### ISSUE THREAD

**Issue by olegmoz** [artipie/npm-adapter#137]
Integration tests are not running in CI pipeline, example is `NpmProxyITCase` class missing in build: https://github.com/artipie/npm-adapter/actions/runs/317180206

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#137` is not assigned, can't get performer
