### ISSUE TITLE
Migrate to HTTP 0.16.7, use BasicAuthSlice

### ISSUE THREAD

**Issue by olegmoz** [artipie/npm-adapter#140]
Migrate to HTTP `0.16.7`, use `BasicAuthSlice` instead of deprecated `SliceAuth` and `Identities`

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.7`

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#140` is not assigned, can't get performer
