### ISSUE TITLE
NpmProxyITCase.java:58-62: Fix NPM proxy integration...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-adapter#144]
The puzzle `141-ed29e327` from #141 has to be resolved: 

https://github.com/artipie/npm-adapter/blob/6a98c8469b7ac175e9a0e25d174baaac5a607838/src/test/java/com/artipie/npm/proxy/NpmProxyITCase.java#L58-L62

The puzzle was created by Oleg Mozzhechkov on 23-Oct-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#144` is not assigned, can't get performer
