### ISSUE TITLE
Trim path for NpmProxySlice

### ISSUE THREAD

**Issue by genryxy** [artipie/npm-adapter#148]
In Artipie module for most adapters method for trimming request line is used (`TrimPathSlice`). But for `npm-proxy` this method breaks implementation. It's necessary to investigate is it possible to create path patterns in `NpmProxySlice` that would be valid after trimming path with `TrimPathSlice`. See this issue for more information (artipie/artipie#738)

**Comment by olenagerasimova** [comment]
done in #299
