### ISSUE TITLE
【bug】this.json.getString(NpmPublishJsonToMetaSkelethon.READM may throw null point exception

### ISSUE THREAD

**Issue by dingdaoyi** [artipie/npm-adapter#150]
npm publish tgz package 
eg：
{
    "_id": "@ironfang-js/ironfang-js",
    "name": "@ironfang-js/ironfang-js",
    "description": "Ironfang Web Framework",
    "dist-tags": {
        "latest": "0.0.1"
    },
    "versions": {
        "0.0.1": {
            "name": "@ironfang-js/ironfang-js",
            "version": "0.0.1",
            "description": "Ironfang Web Framework",
            "main": "./lib/cjs/index.js",
            "module": "./lib/esm/index.js",
            "files": [
                "lib/"
            ],
            "scripts": {
                "tsc": "tsc -p tsconfig.json && tsc -p tsconfig-cjs.json",
                "prepublish": "npm run tsc",
                "test": "echo \"Error: no test specified\" && exit 1"
            },
            "repository": {
                "type": "git",
                "url": "git+https://github.com/ironfang-js/ironfang-js.git"
            },
            "keywords": [],
            "author": "Richard Adnams",
            "license": "MIT",
            "bugs": {
                "url": "https://github.com/ironfang-js/ironfang-js/issues"
            },
            "homepage": "https://github.com/ironfang-js/ironfang-js#readme",
            "devDependencies": {
                "typescript": "3.9.6"
            },
            "_id": "@ironfang-js/ironfang-js@0.0.1",
            "_integrity": "sha512-NEeUulXc+sTPPquy9gHFfsi6xS/hmIWkC84kLS8F7pcqQhgqIhz7KrKJBDETlR6P0GTzgc6XK7gWVzZALJR9uw==",
            "_resolved": "C:\\Users\\dwx881620\\Downloads\\ironfang-js-0.0.1.tgz",
            "_from": "file:ironfang-js-0.0.1.tgz",
            "_nodeVersion": "12.14.1",
            "_npmVersion": "7.3.0",
            "dist": {
                "integrity": "sha512-NEeUulXc+sTPPquy9gHFfsi6xS/hmIWkC84kLS8F7pcqQhgqIhz7KrKJBDETlR6P0GTzgc6XK7gWVzZALJR9uw==",
                "shasum": "5ccdb603d52da44f410f657e38eedbb4761ea065",
                "tarball": "http://localhost:8080/artifactory/api/npm/npm-dev-local1/@ironfang-js/ironfang-js/-/@ironfang-js/ironfang-js-0.0.1.tgz"
            }
        }
    },
    "access": null,
    "_attachments": {
        "@ironfang-js/ironfang-js-0.0.1.tgz": {
            "content_type": "application/octet-stream",
            "data": "H4sIAAAAAAAACu1ZbW/aSBDuZyT+w8iVqkR1wZBAdKl6OgdMYx1gZJzmortTZewFNjVea3edBEX57zdrm5SEXHtVE6pr/AjJ9szsvO3OvpH4wSd/Rup9u2MNx9aLp4BhGO12Gx6iI5oNowEv9lpto9Fot419eGE0jGZ7D59P4s09pEL6HF35Xj15MHD7/J9gYHvQpwGJBalWqpUOS5aczuYSdoJdaBpNAyhn8dSPZ2/OhZIYEb6gQlAWAxUwJ5xMljDjfixJqMOUEwJsCsHc5zOig2Tgx0tICBfYgE2kT2Maz8CHAC1VKygq56hHsKm89DlB6RB8IVhAfVQIIQvSBYmlL5XBKY2IgB05J6CNixbabmYlJH5UrdAYFHPFg0sq5yyVwImQnAZKiQ40DqI0VF6s2BFd0MKEap4lAINFtanAIJSrOixYSKfqSbLIknQSUTHXIaRK9ySVSBSKmCVTV5HUGQdBInQMVVB0PQv3s3+ZkPI+UUmVRZqEolzO2eJuLBQ9mqY8RqMkaxQyTFtm85wEUlGU/JRFEbtU0QUsDqkKShyqjvOQ6U/YBcniyTs5ZhLdzb1Q3ZB87tyCJeZ+FMGEFFlDy5hjfz0krjzAIool9SNIGM9M3g+1lrlwbMHY6XmnpmuBPYaR63ywu1YXNHOM35oOp7Z37Jx4gBKuOfTOwOmBOTyD3+1hVwfrj5FrjcfguNWKPRj1bQuJ9rDTP+naw/dwhA2HDo5nG0c1avUcUBYLXbY1VtoGlts5xk/zyO7b3plerfRsb6i09hwXTBiZrmd3TvqmC6MTd+SMLXSgi3qH9rDnohlrYA29GppFGlgf8APGx2a/r2xVK+YJBuAqF6HjjM5c+/2xB8dOv2sh8chC38yjvpXbwrg6fdMe6NA1B+Z7K2vloBoMT8nlDsLpsaVoyqKJv45nO0MVSccZei5+6hio6922PbXHlg6ma49VTnquM8AYVU6xiZNpwYZDK1ej8g13ugVF1PfJ2LrVCF3L7KOysWqcRbmSxl790RNYie9CUqz/EZ3Ug3NRp3FIrmrn4jFtfHn9N5p7xv31v9lsNcr1fxvQcIWDfHHU3uI8ka0ltZBMaUxGnOGCIJc75EpN60IH7eNHIgYsTCOCk/U1XPhRSg5B8pTAzS62LyRrfhjCO7hgNARjg7xzpcNyF979CtfVCiA4kbiwwRW8hiVK37wtp5VtYb3+iVj8iPo32geb9a/ky/p/euSVqfaKQkJZns8O6/X/FLWv8O3132gZzbL+t4Gy/p83VvVfPLH6WfzYNr5c/w0s/c36bx2U9b8NXGOFa7G/INohaL+t3fXV1941XUldEK5uhpSgUTNqjZwaEhFwmsiCYxet4JRMoMdR8SXjn3LRhU8zmdrGabPg5weLW4n1/WgukV0AosCf2bykKSENX//OmLkfin2ds6UIlDJ8wJsE8IGu0Vk2xOHVK7hHf4MOZbzMFDZPOCku+ZSWOFkAT2MlvhKQREjFIsGcwV+axTnjhxAzUAwQCQnolJLwL01ZI1dUQkN5e5N5i8qZoJLx5ZrDyyQLf0blykbKo4Lyei5lIg7rdXyfp5NawBb1f+mvmlJwa+kTWWIfhFne8kz5qZwzrvS6VN3UhmCGOAaKJBc3mIo9sL2cNklna4ktnPrvDtWpECn23K1Pc7YgCc4336bmJSd+iEO1GHgXXZIQHB9xQIm4m8V8LCjte7Vfau3McOWmXLY2sJr/XcvsDqzaInwCG1/b/+1v7P+M1v5+Of9vAy/v/r/z8PRd7vd+Wjx8/xvW5COeAr9W/wetjfufVqOs/62gOP+FJIjUn4y358BDPAbiXiZdTAjH4+DqNTsW5q/lKfBnwMP3vz++/pvl/z9bQVn/zxub97+PW/sK317/jYO9Vln/20BZ/yVKlCjxPPEP5fZfBAAuAAA=",
            "length": 1445
        }
    }
}

**Comment by olegmoz** [comment]
@rultor release, tag=`0.7.12`

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#150` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@dingdaoyi version `0.7.12` has been released and contains fix for the bug

**Comment by dingdaoyi** [comment]
Thank's. We've upgraded to version 0.7.12.
there are several issues that need to be optimized：
1,TgzArchive,NpmPublishJsonToMetaSkelethon,Meta Should be pubic class,or please complete Npm#updateMetaFile method
2,com.artipie.npm.Tarballs#updateJson JsonPatchBuilder has poor performance in multi-version replacement and is not as good as JsonObjectBuilder.
3,npm unpublish, npm dist-tags,npm deprecate should be supported
