### ISSUE TITLE
Support `npm deprecate`

### ISSUE THREAD

**Issue by genryxy** [artipie/npm-adapter#156]
It is necessary to provide support for `npm deprecate` command. Investigate this issue and add this feature. https://docs.npmjs.com/cli/v6/commands/npm-deprecate From: #150 (comment)

**Comment by 0crat** [comment]
You @genryxy[/z](https://www.0crat.com/u/genryxy) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by g4s8** [comment]
@rultor release, tag=`0.8`
