### ISSUE TITLE
Code coverage metrics

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/npm-adapter#164]
Let's set code coverage metrics values with the help of jacoco plugin, add codecov gitlab action and corresponding badge to readme.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#168](https://github.com/artipie/npm-adapter/issues/168) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#190](https://github.com/artipie/npm-adapter/issues/190) is still not solved; solved: [#168](https://github.com/artipie/npm-adapter/issues/168).

**Comment by 0pdd** [comment]
@olenagerasimova all 2 puzzles are solved here: [#168](https://github.com/artipie/npm-adapter/issues/168), [#190](https://github.com/artipie/npm-adapter/issues/190).
