### ISSUE TITLE
miss some necessary information for latest version

### ISSUE THREAD

**Issue by y00437830** [artipie/npm-adapter#17]
It would cause download failure when the user does not have an explicit version. (latest version is the default version)
For example, npm install @avenueui/harano6@1.0.0 is OK, however, npm install @avenueui/harano6 will be failed.
The package.json file generated By artipie/npm-adapter.

![1](https://user-images.githubusercontent.com/34901207/74820680-66bd1680-533d-11ea-9844-fd3cacb61252.png)
![2](https://user-images.githubusercontent.com/34901207/74820692-69b80700-533d-11ea-8cc1-94e7358488ed.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@y00437830[/z](https://www.0crat.com/u/y00437830) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#17](https://github.com/artipie/npm-adapter/issues/17) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/76e42c26-7353-4eea-9336-d7dcabab64df); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Thanks for your contribution, @y00437830[/z](https://www.0crat.com/u/y00437830)! If you would be a member of [the project](https://www.0crat.com/p/CT2E6TK9B), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @sammers21[/z](https://www.0crat.com/u/sammers21)
