### ISSUE TITLE
Need intercept the address

### ISSUE THREAD

**Issue by y00437830** [artipie/npm-adapter#18]
If we don’t intercept the address, it would cause download failure when we use a remote repository or virtual repository. Since the npm client would use the native address instead of the proxy address. 
Please cut the address prefix, the npm client would assemble the proxy address prefix automatically.
The package.json file generated by artipie/npm-adapter.

![3](https://user-images.githubusercontent.com/34901207/74820875-b4d21a00-533d-11ea-8616-2359916b5345.png)
![4](https://user-images.githubusercontent.com/34901207/74820878-b6034700-533d-11ea-8ccc-65d275b6e90f.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@y00437830[/z](https://www.0crat.com/u/y00437830) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Thanks for your contribution, @y00437830[/z](https://www.0crat.com/u/y00437830)! If you would be a member of [the project](https://www.0crat.com/p/CT2E6TK9B), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#18](https://github.com/artipie/npm-adapter/issues/18) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/37257c04-85f8-4b7b-892d-c803d9cf263d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @sammers21[/z](https://www.0crat.com/u/sammers21)

**Comment by y00437830** [comment]
not cloase

**Comment by y00437830** [comment]
not close, look at my email
