### ISSUE TITLE
    Exact match is used to obtain files from .tgz files. Fuzzy match may fail to obtain correct files.

### ISSUE THREAD

**Issue by dingdaoyi** [artipie/npm-adapter#184]
for example, multiple files in the compressed package have the same name but different paths.
at:
com.artipie.npm.TgzArchive#file

**Comment by genryxy** [comment]
@dingdaoyi thanks for your report. Could you attach example of this archive for a clearer understanding of the issue?

**Comment by genryxy** [comment]
@dingdaoyi  could you attach example of archive for a clearer understanding of the issue?

**Comment by 0crat** [comment]
You @genryxy[/z](https://www.0crat.com/u/genryxy) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#184` is not assigned, can't get performer

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.3`
