### ISSUE TITLE
NPM - local registry

### ISSUE THREAD

**Issue by genryxy** [artipie/npm-adapter#188]
The main functionality that the npm-adapter should support:

- [x] `npm publish`
- [x] `npm install`
- [x] `npm dist-tag` (add, rm, ls)
- [x] authentication & authorisation
- [x] `npm deprecate` (single version and un-deprecate with `""`)
- [x] `npm unpublish`
  - [x] package
  - [x] version
- [x] publish through `curl PUT archive-name.tgz`

**Comment by genryxy** [comment]
@g4s8 please take a look

**Comment by 0crat** [comment]
Job [#188](https://github.com/artipie/npm-adapter/issues/188) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#188` is not assigned, can't get performer
