### ISSUE TITLE
package-info.java:29-32: Improve code coverage for missed...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-adapter#190]
The puzzle `168-faf64628` from #168 has to be resolved: 

https://github.com/artipie/npm-adapter/blob/728411d8e0ce4a511b2d82d74387341f5d0cca42/src/main/java/com/artipie/npm/package-info.java#L29-L32

The puzzle was created by @baudoliver7 on 08-Feb-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `168-faf64628` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#190](https://github.com/artipie/npm-adapter/issues/190) is not in the agenda of @andreoss[/z](https://www.0crat.com/u/andreoss), can't set title
