### ISSUE TITLE
4 situation for intercep the address ?

### ISSUE THREAD

**Issue by y00437830** [artipie/npm-adapter#28]
There is a problem in tarball interception.
Now, the adapter logic is 
Input http://localhost:8080/artifactory/api/npm/npm-test-local-1/@scope/yuanye05/-/@scope/yuanye05-1.0.3.tgz
Use the pattern to matcher and cut the prefix to fixed the issue https://github.com/artipie/npm-adapter/issues/18

However, it Overcorrect.
     We have three situations:
(1)	http://localhost:8080/artifactory/api/npm/npm-test-local-1/@scope/yuanye05/-/@scope/yuanye05-1.0.3.tgz  (npm client with scope)
(2)	http://localhost:8080/artifactory/api/npm/npm-test-local-1/yuanye05/-/yuanye05-1.0.3.tgz (npm client without scope)
(3)	http://localhost:8080/artifactory/api/npm/npm-test-local-1/@scope/yuanye05/yuanye05-1.0.3.tgz (curl with scope)
(4)	http://localhost:8080/artifactory/api/npm/npm-test-local-1/yuanye05/yuanye05-1.0.3.tgz (curl without scope)

so in the other three（2，3，4） situations, the matcher would throw not match exception.
How about I use a Method parameter to give you the prefix waited to be cut???( I give you the **http://localhost:8080/artifactory/api/npm/npm-test-local-1/**)  

If you agree, you can define a new parameter? Or else we can use the “pathpref”, although I know the “pathpref” original design was meant to add prefixes, not to cut them off.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@y00437830[/z](https://www.0crat.com/u/y00437830) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@rultor release, tag=`0.3.3`

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#28` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@rultor release, tag=`0.3.3`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@e6cb530cd606, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Adapter back end integration' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.51.7](https://github.com/zerocracy/farm): CID: [09833fab-5489-4c64-aa2e-f52bf1d9691d](https://www.0crat.com/footprint/CT2E6TK9B/09833fab-5489-4c64-aa2e-f52bf1d9691d), Type: "Job milestoned"

**Comment by y00437830** [comment]
Different from the first and second way， （3）（4）These two methods are provided for users to use flexibly. 
At present, we see that some users will add version level directories.
like 
(3)	http://localhost:8080/artifactory/api/npm/npm-test-local-1/@scope/yuanye05/1.0.3/XXX/yuanye05-1.0.3.tgz (curl with scope)
(4)	http://localhost:8080/artifactory/api/npm/npm-test-local-1/yuanye05/1.0.3/XXX/yuanye05-1.0.3.tgz

<YOUR_COOL_PACKAGE_NAME>/<VERSION_NAME>/<FILE_TARGET_PATH>/

so, Regular expressions need to be updated. Or consider that I can directly give you a String parameter of intercept prefix waited to be cut, which may prevent us from repeatedly modifying the regular expression.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by Sammers21** [comment]
@y00437830 , can you refer to the artifactory documentation in the issues concerning prefixes?

**Comment by g4s8** [comment]
@y00437830 closing as outdated, please submit a new issue if you still have a problem.

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#28` is not assigned, can't get performer
