### ISSUE TITLE
HTTP API for npm-adapter

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#31]
Let's add HTTP API as `Slice` implementation for npm adapter.

**Comment by 0crat** [comment]
The job [#31](https://github.com/artipie/npm-adapter/issues/31) assigned to @guseyn[/z](https://www.0crat.com/u/guseyn), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6dbe1697-6630-41a6-95dd-1ab60a7ec760); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @guseyn[/z](https://www.0crat.com/u/guseyn) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@guseyn[/z](https://www.0crat.com/u/guseyn) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @guseyn[/z](https://www.0crat.com/u/guseyn) resigned from [#31](https://github.com/artipie/npm-adapter/issues/31), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#31](https://github.com/artipie/npm-adapter/issues/31) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/68493acb-fb93-4a39-af0e-0ae5c02c9897); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by g4s8** [comment]
@rultor release, tag=`0.4`
