### ISSUE TITLE
NPM adapter configuration

### ISSUE THREAD

**Issue by ChGen** [artipie/npm-adapter#340]
When trying to run simple command on `npm-adapter` with recent versions of npm (below), it requires authentication support right away (on `npm` client side).
So authentication support is required in `npm-adapter`, as well as setup example/instructions.
Also, this is related to issues: #74, #208, #339

```
node -v
v18.9.0

npm -v
8.19.1

cd artipie/npm-adapter/src/test/resources
NODE_DEBUG=http npm publish --registry=http://localhost:8080/ChGen/npmtest ./project-without-scope

npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to http://localhost:8080/ChGen/npmtest
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by 0pdd** [comment]
@ChGen the puzzle [#343](https://github.com/artipie/npm-adapter/issues/343) is still not solved.

**Comment by olenagerasimova** [comment]
auth implemented, check wiki https://github.com/artipie/artipie/wiki/npm
