### ISSUE TITLE
Npm.java:119-124: Implement metadata update by using tgz...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-adapter#36]
The puzzle `27-b5f30c4d` from #27 has to be resolved: 

https://github.com/artipie/npm-adapter/blob/7b306cec039e450c8f0e55a6f571c4362b1e7f90/src/main/java/com/artipie/npm/Npm.java#L119-L124

The puzzle was created by paulodamaso on 17-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@genryxy please check if this task is still valid, and remove this puzzle if it's outdated
