### ISSUE TITLE
dist-tags bug

### ISSUE THREAD

**Issue by y00437830** [artipie/npm-adapter#37]
However, yesterday and today, some high priority users feedback problems by using commander “npm publish –tag alpha”.
It is a small but deadly bug for the adpter. We need fixed it in today.

(1)	When user exec “npm publish”. The upload info example is:
"dist-tags": {
"latest": "1.0.0"
},
(2)	When user exec “npm publish –tag alpha” “npm publish –tag alpha ”
"dist-tags": {
"alpha": "1.0.1"
},

We hope our medate file could be generated into 
"dist-tags": {
"latest": "1.0.0"
"alpha": "1.0.1"
},

yet, our adpter file choose update it all by new info
Our error result: use new dist-tag object Replace old
"dist-tags": {
"alpha": "1.0.1"
},

 

It absolutely a tiny adjustment for code. But，it made Chaos in version management for user.
It is extremely important !!!!!!!!

(3)	If user continue exec “npm publish”
"dist-tags": {
"latest": "1.0.2"
},
We hope our medate file could be generated into 
"dist-tags": {
"latest": "1.0.2"
"alpha": "1.0.1"
},

(4)	If user continue exec “npm publish –tag alpha””
"dist-tags": {
"alpha": "1.0.3"
},
We hope our medate file could be generated into 
"dist-tags": {
"latest": "1.0.2"
"alpha": "1.0.3"
},

(5)	If user continue exec “npm publish –tag “${tag}”
"dist-tags": {
“${tag}”: "${newVersion}"
},
We hope our medate file could be generated into 
"dist-tags": {
"latest": "1.0.2"
"alpha": "1.0.3"
“${tag}”: "${newVersion}"

},

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign @Sammers21

**Comment by 0crat** [comment]
> @0crat assign @Sammers21  ([here](https://github.com/artipie/npm-adapter/issues/37#issuecomment-603795981))

@g4s8 The job [#37](https://github.com/artipie/npm-adapter/issues/37) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f93b8458-f814-4a8d-a70f-9c41b0b96ffd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.1`

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
