### ISSUE TITLE
No test upload slice

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#42]
Add a test to verify that `UploadSlice` is working correctly.

**Comment by 0crat** [comment]
The job [#42](https://github.com/artipie/npm-adapter/issues/42) assigned to @guseyn[/z](https://www.0crat.com/u/guseyn), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b7d5e6ee-fbb9-4d25-a203-bcfbf6aac6fb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @guseyn[/z](https://www.0crat.com/u/guseyn) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@guseyn[/z](https://www.0crat.com/u/guseyn) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@rultor release, tag=`0.5`

**Comment by 0crat** [comment]
Job [#42](https://github.com/artipie/npm-adapter/issues/42) is not in the agenda of @guseyn[/z](https://www.0crat.com/u/guseyn), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @guseyn[/z](https://www.0crat.com/u/guseyn), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#42](https://github.com/artipie/npm-adapter/issues/42) is not in the agenda of @guseyn[/z](https://www.0crat.com/u/guseyn), can't set title

**Comment by sereshqua** [comment]
@0crat quality good
