### ISSUE TITLE
UploadSlice does not publish

### ISSUE THREAD

**Issue by olegmoz** [artipie/npm-adapter#48]
UploadSlice does not await for 'npm.publish()' call to finish successfully before responding with OK.
In fact the call ends with exception wight now, which may be seen by replacing `thenRunAsync` with `thenCompose`:
```
.thenRunAsync(() -> this.npm.publish(...))
```
with
```
.thenCompose(ignored  -> this.npm.publish(...))
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
Fixed
