### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#49]
`npm` CLI tool can publish packages to npm repository, but can't install it.

Steps to reproduce:
 1. Run Artipie server with npm repository enabled (I used `javas` name)
 2. Publish package to repository: go to any javascript package sources and run `npm --registry=http://localhost/javas/ publish`
 3. Try to install same package: `npm --registry=http://localhost/javas/ install <package-name>`

Result: 404 error
```
npm ERR! code E404
npm ERR! 404 Not Found - GET http://localhost/javas/foo
npm ERR! 404 
npm ERR! 404  'foo@0.1.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

On publish Artipie web server printed:
```
com.artipie.Pie - Request: PUT /javas/foo HTTP_1_1
```
On installation:
```
com.artipie.Pie - Request: GET /javas/foo HTTP_1_1
```

**Comment by 0crat** [comment]
The job [#49](https://github.com/artipie/npm-adapter/issues/49) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0947052a-ee92-4aee-95c8-6151f1fd9829); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#63](https://github.com/artipie/npm-adapter/issues/63) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.6`

**Comment by g4s8** [comment]
@rultor release, tag=`0.6`

**Comment by g4s8** [comment]
@brastak thanks, closing this bug. It was released as `0.6`, can you update NPM version in Artipie main repo?

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @brastak[/z](https://www.0crat.com/u/brastak), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#63](https://github.com/artipie/npm-adapter/issues/63) is solved here.
