### ISSUE TITLE
Add authentication to npm adapter

### ISSUE THREAD

**Issue by IlyaMoskva** [artipie/npm-adapter#50]
Add basic authentication to npm adapter and authorize users for upload and download.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#50](https://github.com/artipie/npm-adapter/issues/50) assigned to @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/373b7b79-4a3c-48b1-befe-307d6dabdb90); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c08ec908-6891-4027-9aad-79415e47ffee, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pmo.awards.penalize_for_same_user_github_assignment
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.53.11](https://github.com/zerocracy/farm): CID: [373b7b79-4a3c-48b1-befe-307d6dabdb90](https://www.0crat.com/footprint/CT2E6TK9B/373b7b79-4a3c-48b1-befe-307d6dabdb90), Type: "Start order"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c08ec908-6891-4027-9aad-79415e47ffee, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.in.orders.start_order_if_assigned_in_github
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.53.11](https://github.com/zerocracy/farm): CID: [7678749f-f89b-48d4-b40a-7f5064c65842](https://www.0crat.com/footprint/CT2E6TK9B/7678749f-f89b-48d4-b40a-7f5064c65842), Type: "Job was added to WBS"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c08ec908-6891-4027-9aad-79415e47ffee, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.cost.pay_per_github_bug
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.53.11](https://github.com/zerocracy/farm): CID: [7678749f-f89b-48d4-b40a-7f5064c65842](https://www.0crat.com/footprint/CT2E6TK9B/7678749f-f89b-48d4-b40a-7f5064c65842), Type: "Job was added to WBS"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c08ec908-6891-4027-9aad-79415e47ffee, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.staff.bans.ban_github_reporter
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.53.11](https://github.com/zerocracy/farm): CID: [7678749f-f89b-48d4-b40a-7f5064c65842](https://www.0crat.com/footprint/CT2E6TK9B/7678749f-f89b-48d4-b40a-7f5064c65842), Type: "Job was added to WBS"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c08ec908-6891-4027-9aad-79415e47ffee, thread: PQ-CT2E6TK9B
com.jcabi.github.RtValuePagination$Items[181] java.lang.IllegalStateException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.53.11](https://github.com/zerocracy/farm): CID: [7678749f-f89b-48d4-b40a-7f5064c65842](https://www.0crat.com/footprint/CT2E6TK9B/7678749f-f89b-48d4-b40a-7f5064c65842), Type: "Job was added to WBS"

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/npm-adapter/issues/50#issuecomment-619065522))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#50](https://github.com/artipie/npm-adapter/issues/50) is [in scope](http://www.zerocracy.com/policy.html#14) for 1days
  * The role is `DEV`
  * The job is assigned to @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva) for [1days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fnpm-adapter%2350%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@IlyaMoskva PR was merged, thanks.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @ilyamoskva[/z](https://www.0crat.com/u/ilyamoskva), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@IlyaMoskva @g4s8 

Problem reporter and problem solver should be two different persons

**Comment by sereshqua** [comment]
@0crat quality acceptable
