### ISSUE TITLE
Enable coverage reports

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#52]
Generate test coverage reports to upload to codecov, see https://github.com/artipie/npm-adapter/runs/632956472

**Comment by 0crat** [comment]
The job [#52](https://github.com/artipie/npm-adapter/issues/52) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/346afc71-7403-492b-b4f7-a762da4275cb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-adapter/issues/52#issuecomment-625000959))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#52](https://github.com/artipie/npm-adapter/issues/52), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#52](https://github.com/artipie/npm-adapter/issues/52) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8de81453-ba40-451f-a997-8d2e087de51a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for artipie/ppom#20 to be merged

**Comment by victornoel** [comment]
@0crat wait for artipie/ppom#21 to be merged

**Comment by 0crat** [comment]
> @0crat wait for artipie/ppom#21 to be merged ([here](https://github.com/artipie/npm-adapter/issues/52#issuecomment-627820597))

@victornoel Job [#52](https://github.com/artipie/npm-adapter/issues/52) is already on hold

**Comment by victornoel** [comment]
@0crat wait for #60 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #60 to be merged ([here](https://github.com/artipie/npm-adapter/issues/52#issuecomment-629410094))

@victornoel Job [#52](https://github.com/artipie/npm-adapter/issues/52) is already on hold

**Comment by victornoel** [comment]
@g4s8 can you close this? The PR was merged and everything seems to work: https://codecov.io/gh/artipie/npm-adapter/branch/master

**Comment by victornoel** [comment]
@g4s8 can you close this?

**Comment by victornoel** [comment]
@g4s8 please can you close it?

**Comment by g4s8** [comment]
@victornoel thanks

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#52` is not assigned, can't get performer

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/npm-adapter/issues/52#issuecomment-633595367))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#52](https://github.com/artipie/npm-adapter/issues/52) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fnpm-adapter%2352%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@g4s8 I think 0crat missed this one

**Comment by g4s8** [comment]
@0crat pay 30min @victornoel
