### ISSUE TITLE
UploadSliceTest.java:63: Rewrite test method to be able...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-adapter#54]
The puzzle `53-d5b414c9` from #53 has to be resolved: 

https://github.com/artipie/npm-adapter/blob/04d802b0ceccefec5d29e3261ad1a997fe451562/src/test/java/com/artipie/npm/http/UploadSliceTest.java#L63-L63

The puzzle was created by brastak on 08-May-20. 

Estimate: 45 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#54](https://github.com/artipie/npm-adapter/issues/54) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/cc68a6f8-2370-4815-ba04-0c38f6a0fb82); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by olegmoz** [comment]
@brastak could you please clarify what this issue is about?

**Comment by brastak** [comment]
@olegmoz This test was written by Guseyn and should verify UploadSlice works correctly (as I think). Now it fails and the checks are partly redundant and partly incorrect. Test should be rewritten:
1) new payload should be generated;
2) we don't need to check Storage state here, it's too heavy. I think, it will be enough to check correspondent mocks to be called

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
