### ISSUE TITLE
Incorrect copyright in license

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/npm-adapter#58]
Please, check license, it's incorrect: Yegor instead of Artipie.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#58](https://github.com/artipie/npm-adapter/issues/58) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ef6ed169-ded2-468f-887a-75db58c4c004); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #66 to be merged

**Comment by victornoel** [comment]
@olenagerasimova it's done in #66, can you close this issue? :)

**Comment by olenagerasimova** [comment]
@victornoel sure, thanks)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
