### ISSUE TITLE
ASTO version update

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#61]
Update asto dependency version to >= `0.20`

**Comment by 0crat** [comment]
The job [#61](https://github.com/artipie/npm-adapter/issues/61) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/991b9ccf-6196-4fd3-8f6d-afc458074a60); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@brastak fixed by `0.20.3`

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#61` is not assigned, can't get performer
