### ISSUE TITLE
Codecov reports

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#62]
Update parent pom to the latest available version and enable `jacoco` plugin to generate reports for codecov. Also, add the badge to readme file to see the coverage percentage. See RPM adapter for example: https://github.com/artipie/asto

**Comment by 0crat** [comment]
The job [#62](https://github.com/artipie/npm-adapter/issues/62) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/92441b27-fec6-4331-9de2-6b7f19ba83b2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@brastak sorry, it's a duplicate of #52

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @brastak[/z](https://www.0crat.com/u/brastak), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)
