### ISSUE TITLE
DownloadPackageSlice.java:50: handle https schema in the...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-adapter#63]
The puzzle `49-ba9c0273` from #49 has to be resolved: 

https://github.com/artipie/npm-adapter/blob/1ae2da329108909e89c7bb5e95238c9c0a1dc17d/src/main/java/com/artipie/npm/http/DownloadPackageSlice.java#L50-L50

The puzzle was created by brastak on 14-May-20. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#63](https://github.com/artipie/npm-adapter/issues/63) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/52545eb3-c760-4ec7-9aec-6dc6f0e617a8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job
