### ISSUE TITLE
The badges in the README still points to travis

### ISSUE THREAD

**Issue by victornoel** [artipie/npm-adapter#65]
I think we moved to Github actions but the badges in the README still points to travis.

Also there are no badges for coverage

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel thanks, fixed in https://github.com/artipie/npm-adapter/commit/378a701e75a775cdd1475ab3db7af666058f693b

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#65` is not assigned, can't get performer
