### ISSUE TITLE
NpmCommandsTest.java:82-84: remove the loop with...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-adapter#67]
The puzzle `64-0c89f1b5` from #64 has to be resolved: 

https://github.com/artipie/npm-adapter/blob/430067da28fa7990de823767a6f4a88dccae5d97/src/test/java/com/artipie/npm/NpmCommandsTest.java#L82-L84

The puzzle was created by brastak on 21-May-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#67` is not assigned, can't get performer
