### ISSUE TITLE
NpmCommandsTest.java:178-181: transform method into...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-adapter#68]
The puzzle `64-5e3ded21` from #64 has to be resolved: 

https://github.com/artipie/npm-adapter/blob/430067da28fa7990de823767a6f4a88dccae5d97/src/test/java/com/artipie/npm/NpmCommandsTest.java#L178-L181

The puzzle was created by brastak on 21-May-20. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#68](https://github.com/artipie/npm-adapter/issues/68) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/918ab32b-b2a6-4e01-a8b6-d308f0e95fcd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#68` is not assigned, can't get performer
