### ISSUE TITLE
Remove Thread.sleep from test

### ISSUE THREAD

**Issue by Sammers21** [artipie/npm-adapter#69]
When a package is published -> metadata is generated/updated. No need to Thread.sleep

https://github.com/artipie/npm-adapter/blob/ae73bc2f95217ad29504b11ac3cd212e81a95d1b/src/test/java/com/artipie/npm/NpmCommandsTest.java#L104

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 metadata update is starting asynchronously, how do you suggest to get rid of `sleep` here?
@brastak

**Comment by Sammers21** [comment]
@g4s8, to make it synchronous for a user.

**Comment by Sammers21** [comment]
@g4s8, as a user I expect a package to be available as soon as published operation exited

**Comment by genryxy** [comment]
@olegmoz it looks like duplicate #67

**Comment by olegmoz** [comment]
@genryxy that's right, thanks

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#69` is not assigned, can't get performer
