### ISSUE TITLE
Unable to download NPM package

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#71]
I created simple npm package (see `package.json` in attachments) and successfully published it to Artipie central:
```
$ npm --registry=http://central.artipie.com/npm/ publish
npm notice 
npm notice 📦  js-example@0.1.0
npm notice === Tarball Contents === 
npm notice 22B  index.js    
npm notice 253B package.json
npm notice === Tarball Details === 
npm notice name:          js-example                              
npm notice version:       0.1.0                                   
npm notice package size:  289 B                                   
npm notice unpacked size: 275 B                                   
npm notice shasum:        27578f8d602004d07d7a6575dd3c298c9a8856aa
npm notice integrity:     sha512-u+XO4jFECBHOO[...]DV3zyTfrbv6/g==
npm notice total files:   2                                       
npm notice 
+ js-example@0.1.0
```
This command generated a file at `/npm/js-example/-/js-example-0.1.0.tgz` in cloud storage (see file in attachments). But when I tried to install this package from registry, I got an error:
```
$ npm --registry=http://central.artipie.com/npm/ install js-example
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://artipie/js-example/-/js-example-0.1.0.tgz failed, reason: getaddrinfo ENOTFOUND artipie
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/g4s8/.npm/_logs/2020-05-25T12_24_00_785Z-debug.log
```
It's strange that it's failing with error `http://artipie/js-example/-/js-example-0.1.0.tgz failed, reason: getaddrinfo ENOTFOUND artipie`, because host is wrong here, it should be `http://central.artipie.com/...` instead of `http://artipie/`.

Archive with attachments (`package.json`, `debug.log` and `js-example-0.1.0.tgz` from central npm repo) [debug.tar.gz](https://github.com/artipie/npm-adapter/files/4677154/debug.tar.gz)

**Comment by 0crat** [comment]
The job [#71](https://github.com/artipie/npm-adapter/issues/71) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/045cff3b-9249-4ede-b63d-df289e49f79c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by brastak** [comment]
@g4s8 Please, describe deployment schema that in use. As I see, response contains Server: nginx header. I suggest, that we have nginx before artipie as reverse proxy. Neither NPM nor NPM-proxy currently not supports reverse proxy.
We need to implement this feature and setup nginx to add X-Forwarded-* headers.

**Comment by g4s8** [comment]
@brastak you can find Central configuration environment in github.com/artipie/central/ repo, I've added `proxy_set_header Host $host;` to Nginx config, and it was fixed.

**Comment by 0crat** [comment]
Job was finished in 25 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @brastak[/z](https://www.0crat.com/u/brastak), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)
