### ISSUE TITLE
Published package not found 404

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#72]
I've successfully published a package (same as in https://github.com/artipie/npm-adapter/issues/71 ticket), but unable to install it:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   '--registry=https://central.artipie.com/npm',
1 verbose cli   'install',
1 verbose cli   'js-example@0.1.0'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.16.1
4 verbose npm-session 7e8fd00ca67b68e8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://central.artipie.com/npm/js-example 1285ms
8 http fetch GET 404 https://central.artipie.com/js-example/-/js-example-0.1.0.tgz 302ms
9 silly fetchPackageMetaData error for js-example@0.1.0 404 Not Found - GET https://central.artipie.com/js-example/-/js-example-0.1.0.tgz
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 1615ms
12 verbose stack Error: 404 Not Found - GET https://central.artipie.com/js-example/-/js-example-0.1.0.tgz
12 verbose stack     at /usr/lib64/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
13 verbose statusCode 404
14 verbose pkgid js-example@0.1.0
15 verbose cwd /home/projects/github.com/g4s8/js-example
16 verbose Linux 5.4.28-gentoo-x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "--registry=https://central.artipie.com/npm" "install" "js-example@0.1.0"
18 verbose node v12.16.1
19 verbose npm  v6.14.5
20 error code E404
21 error 404 Not Found - GET https://central.artipie.com/js-example/-/js-example-0.1.0.tgz
22 error 404
23 error 404 'js-example@0.1.0' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
```

**Comment by 0crat** [comment]
The job [#72](https://github.com/artipie/npm-adapter/issues/72) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5b6d19e8-dab8-4a78-81fa-023337c8641f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by brastak** [comment]
@g4s8 It will be fixed together w/ https://github.com/artipie/artipie/pull/174 (just correct NpmSlice initialization is required)

**Comment by brastak** [comment]
@g4s8 the related fix was merged, please close if the fix solved the problem

**Comment by g4s8** [comment]
@brastak thanks

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#72` is not assigned, can't get performer
