### ISSUE TITLE
500 error on publish

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#73]
I tried to publish the same test package as in https://github.com/artipie/npm-adapter/issues/71#issue-624272815 ticket, I added valid credentials to `~/.rpmrc`, I see headers are ok and Artipie accepted the user, but it returns 500 error after about 10 seconds of waiting:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   '--registry=https://central.artipie.com/npm/',
1 verbose cli   'publish'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.16.1
4 verbose npm-session 5e7af0ee2f3c723b
5 verbose publish [ '.' ]
6 info lifecycle js-example@0.1.0~prepublish: js-example@0.1.0
7 info lifecycle js-example@0.1.0~prepare: js-example@0.1.0
8 info lifecycle js-example@0.1.0~prepublishOnly: js-example@0.1.0
9 info lifecycle js-example@0.1.0~prepack: js-example@0.1.0
10 info lifecycle js-example@0.1.0~postpack: js-example@0.1.0
11 notice
12 notice 📦  js-example@0.1.0
13 notice === Tarball Contents ===
14 notice 22B  index.js
14 notice 253B package.json
15 notice === Tarball Details ===
16 notice name:          js-example
16 notice version:       0.1.0
16 notice package size:  289 B
16 notice unpacked size: 275 B
16 notice shasum:        27578f8d602004d07d7a6575dd3c298c9a8856aa
16 notice integrity:     sha512-u+XO4jFECBHOO[...]DV3zyTfrbv6/g==
16 notice total files:   2
17 notice
18 http fetch PUT 500 https://central.artipie.com/npm/js-example 71883ms attempt #3
19 verbose stack Error: 500 Internal Server Error - PUT https://central.artipie.com/npm/js-example
19 verbose stack     at /usr/lib64/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
19 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
20 verbose statusCode 500
21 verbose pkgid js-example@0.1.0
22 verbose cwd /home/projects/github.com/g4s8/js-example
23 verbose Linux 5.4.28-gentoo-x86_64
24 verbose argv "/usr/bin/node" "/usr/bin/npm" "--registry=https://central.artipie.com/npm/" "publish"
25 verbose node v12.16.1
26 verbose npm  v6.14.5
27 error code E500
28 error 500 Internal Server Error - PUT https://central.artipie.com/npm/js-example
29 verbose exit [ 1, true ]
```
Artipie logs are empty too, only 500 error.

Other adapters are working fine with same user and same configuration.

Repo config:
```yaml
repo:
  type: npm
  path: npm
  permissions:
    test:
      - download
      - upload
      - delete
    \*:
      - download
```

**Comment by 0crat** [comment]
The job [#73](https://github.com/artipie/npm-adapter/issues/73) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d9c1907a-cfc8-40d3-8367-69fb0b67e991); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by brastak** [comment]
@g4s8 Try to add leading `/` to path

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @brastak[/z](https://www.0crat.com/u/brastak), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)
