### ISSUE TITLE
possible data corruption or http:500 in case of parallel npm package upload

### ISSUE THREAD

**Issue by artemlazarev** [artipie/npm-adapter#78]
If two differet user desides upload the same revision of npm package, UploadSlice.class  will generate 
the same name for temp file.
In that case we must return 409 or do something else. Possible solution: generate random name for temp file on the fly.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@brastak please check this issue

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#78` is not assigned, can't get performer
