### ISSUE TITLE
Integration tests required installed npm tooling

### ISSUE THREAD

**Issue by artemlazarev** [artipie/npm-adapter#80]
Integration tests required installed npm tooling. May be it will be good run integration tests in the container.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@artemlazarev yes, that's good point, I think we need to wrap it with Testcontainers like other integration tests

**Comment by genryxy** [comment]
@olegmoz it looks like duplicate #127

**Comment by olegmoz** [comment]
@genryxy thanks, closing

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#80` is not assigned, can't get performer
