### ISSUE TITLE
Update http and dependency asto

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-adapter#87]
NPM has outdated dependencies incompatible with latest public API: https://github.com/artipie/artipie/issues/350
Let's update `artipie/http` and `artipie/asto` to the latest version to fix that.

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sammers21[/z](https://www.0crat.com/u/sammers21), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by g4s8** [comment]
@rultor release, tag=`0.7`

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by g4s8** [comment]
@rultor release, tag=`0.7`
